-- Generated by scripts/feature-post.mjs. Makes "dental-year-end-benefits-treatment-plans" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'dental-year-end-benefits-treatment-plans';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'dental-year-end-benefits-treatment-plans' AND "status" = 'published';
