-- Generated by scripts/feature-post.mjs. Makes "salon-december-chair-hours-regulars-first" the featured Industry LoogoBlog
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'salon-december-chair-hours-regulars-first';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'salon-december-chair-hours-regulars-first' AND "status" = 'published';
