-- Generated by scripts/feature-post.mjs. Makes "window-cleaning-daylight-saving-last-start-time" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'window-cleaning-daylight-saving-last-start-time';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'window-cleaning-daylight-saving-last-start-time' AND "status" = 'published';
