-- Generated by scripts/feature-post.mjs. Makes "gutter-cleaning-rain-day-reschedule-list" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'gutter-cleaning-rain-day-reschedule-list';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'gutter-cleaning-rain-day-reschedule-list' AND "status" = 'published';
