-- Generated by scripts/feature-post.mjs. Makes "lawn-care-fall-transition-after-last-mow" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'lawn-care-fall-transition-after-last-mow';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'lawn-care-fall-transition-after-last-mow' AND "status" = 'published';
