-- Generated by scripts/feature-post.mjs. Makes "dog-boarding-vaccine-records-before-thanksgiving" the featured Industry LoogoBlog
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'dog-boarding-vaccine-records-before-thanksgiving';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'dog-boarding-vaccine-records-before-thanksgiving' AND "status" = 'published';
