-- Generated by scripts/feature-post.mjs. Makes "plumber-pre-thanksgiving-kitchen-drain-check" the featured Industry LoogoBlog
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'plumber-pre-thanksgiving-kitchen-drain-check';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'plumber-pre-thanksgiving-kitchen-drain-check' AND "status" = 'published';
