-- Generated by scripts/feature-post.mjs. Makes "handyman-celebration-own-one-town" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'handyman-celebration-own-one-town';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'handyman-celebration-own-one-town' AND "status" = 'published';
