// Emits a Netlify DB migration that makes one post the featured LoogoNews post.
//
//   node scripts/feature-post.mjs <slug>
//
// Writes netlify/database/migrations/<timestamp>_feature_<slug>/migration.sql.
// Clears the old featured post before setting the new one: Postgres checks the
// "only one featured post" index (posts_one_featured) row by row, so a single
// statement that flips both rows can fail on whichever row it touches first. The slug must already be in
// content/posts.mjs; the post must be published for the site to show it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { posts } from '../content/posts.mjs';
import { nextStamp } from './generate-post-migration.mjs';

const slug = process.argv[2];
if (!slug) {
  console.error('Usage: node scripts/feature-post.mjs <slug>');
  process.exit(1);
}
if (!posts.some((post) => post.slug === slug)) {
  console.error(`No post with slug "${slug}" in content/posts.mjs`);
  process.exit(1);
}

const lit = `'${slug.replace(/'/g, "''")}'`;
const dir = `netlify/database/migrations/${nextStamp()}_feature_${slug.replace(/-/g, '_').slice(0, 60)}`;
mkdirSync(dir, { recursive: true });
writeFileSync(`${dir}/migration.sql`, `-- Generated by scripts/feature-post.mjs. Makes "${slug}" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> ${lit};
UPDATE "posts" SET "featured" = true WHERE "slug" = ${lit} AND "status" = 'published';
`);
console.log(`Wrote ${dir}/migration.sql`);
