-- Generated by scripts/feature-post.mjs. Makes "massage-therapy-gift-certificate-recipient-booking-nudge" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'massage-therapy-gift-certificate-recipient-booking-nudge';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'massage-therapy-gift-certificate-recipient-booking-nudge' AND "status" = 'published';
