-- Generated by scripts/feature-post.mjs. Makes "holiday-lighting-book-install-and-takedown" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'holiday-lighting-book-install-and-takedown';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'holiday-lighting-book-install-and-takedown' AND "status" = 'published';
