-- Generated by scripts/feature-post.mjs. Makes "chimney-sweep-first-cold-snap-waves" the featured LoogoNews
-- post. Clear first, then set, so posts_one_featured never sees two rows.
UPDATE "posts" SET "featured" = false WHERE "featured" AND "slug" <> 'chimney-sweep-first-cold-snap-waves';
UPDATE "posts" SET "featured" = true WHERE "slug" = 'chimney-sweep-first-cold-snap-waves' AND "status" = 'published';
